# Generated by Django 4.2.1 on 2023-07-22 07:38

from django.db import migrations
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group
import django.db.models.deletion

def link_user_account(apps, schema_editor):
    User = get_user_model()
    SU_Staff = apps.get_model("su_staffs", "SU_Staff")
    su_staffs = SU_Staff.objects.all()
    su_staff_group = Group.objects.get(name="SU Staff Group")

    for su_staff in su_staffs:
        # Generate the username and password
        username = su_staff.staff_id
        password = "init" + su_staff.staff_id
        # Create a new User object

        try:
            user = User.objects.create(
                username=username,
                password=make_password(password),
                is_active=True,
                is_staff=True,
                email="example@sunway.edu.my",
            )
            user.save()
            user.groups.add(su_staff_group)
            user.save()

            userAfter = User.objects.get(username=username)
            su_staff.user_id = userAfter
            su_staff.save()
            print(f"Successfully linked User '{user}' with SU_Staff '{su_staff}'")

        except Exception as e:
            user.delete()
            print(f"An error occurred at user: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(link_user_account),
    ]
